title       = "zippopotam"
baseURL     = "https://zippopotam-cli.tamnd.com/"
description = "A command line for zippopotam."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/zippopotam-cli"
